Page404
dbudwin/RoboHome-Web pull request #166
Opened 2018-10-21 16:35 UTC by kailichiang

## Description
Create a 404 page and CSS.

## Motivation and Context

Redirect 404 response to customized 404 page.

## How Has This Been Tested?

## Screenshots (if appropriate):
![page-404](https://user-images.githubusercontent.com/6218405/47269553-20fa0d80-d592-11e8-969a-16ae98ad39d4.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement/Security (non-breaking change which is not noticeable to end users)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I created a feature branch and did not open a pull request from my `master` branch.
- [x] My code follows the code style of this project.
- [ ] My change requires an update to the README and I have updated it accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] This is a complete change and doesn't leave the project in a bad state.
- [x] All new and existing tests pass.

2018-10-22 23:16 UTC, dbudwin requested changes
I love the 404 page, looks really good.  It's better than anything I would have come up with :)

I'm requesting a few minor changes that will simplify and clean things up a tad.  Lastly, can you please introduce a Dusk test case to verify the error message appears when hitting an erroneous URL?

2018-10-22 23:16 UTC, dbudwin commented on app/Exceptions/Handler.php
> +        if($exception instanceof NotFoundHttpException) {
I don't think this is necessary for Laravel 5.7, I think you can safely revert this whole file.

[Custom Error Messages](https://laravel.com/docs/5.7/errors#custom-http-error-pages)

2018-10-22 23:16 UTC, dbudwin commented on resources/views/404.blade.php
> +@extends('layouts.app')
Move this file into a new folder called `errors` so the file path will be: `resources/views/errors/404.blade.php`

2018-10-22 23:16 UTC, dbudwin commented on resources/views/404.blade.php
> +<link href="https://fonts.googleapis.com/css?family=Poppins:400,700" rel="stylesheet">
I would prefer not to introduce a new font to help keep it looking as similar to the other pages as possible.  When I removed this line and refreshed the page, it still looked pretty similar.  Do you have a compelling case for wanting to use this font?  It does look nice though, just prefer consistency.

2018-10-22 23:16 UTC, dbudwin commented on public/css/404.css
> +
Extra newline, please remove.

2018-10-22 23:16 UTC, dbudwin commented on public/css/404.css
> +  -webkit-box-sizing: border-box;
Can we indent by 4 spaces instead of 2, please?  I'm not a CSS expert, so if there is a convention here that I am unaware of, please let me know.

2018-10-22 23:16 UTC, dbudwin commented on resources/views/devices.blade.php
> +                    }
Please revert this change.

2018-10-22 23:19 UTC, dbudwin commented
Also, please have a look at Code Climate's results from linting the CSS.  I'm not a CSS expert, so I can't weight in very well as to what may or may not need to be changed: https://codeclimate.com/github/dbudwin/RoboHome-Web/pull/166

2018-10-24 15:34 UTC, kailichiang commented
> One more thing, you originally pushed 6 commits, I think you need to update your local `master` to be inline with the remote `master` and rebase this one commit (plus any additional commits you add) on top of the new master.

I will do the update according to your comments. Only this part. I'm not very clear. In fact, I started the branch after syncing with the original master (dbudwin/RoboHome-We). I have no idea is this because I firstly did PR #155 by master branch and got merged. If you can give a piece of guide, it would be very helpful.

2018-10-24 16:13 UTC, dbudwin commented
> I have no idea is this because I firstly did PR #155 by master branch and got merged

This would be my guess which is why I try to make sure I never do work on my `master` branch.  You may need to try something like the following:

```
git remote add upstream https://github.com/dbudwin/RoboHome-Web
git checkout master
git pull upstream master # Hopefully now your local master matches the remote master
git checkout page404
git rebase -i master
# Do the rebase work here
git push --force-with-lease origin page404
```

Then, during the interactive rebase only `pick` the actual commit and delete the other lines (I'm assuming you can use `vim` here a little bit).  I _believe_ this should fix it for you.  Ultimately, you want to make sure your local `master` is set to the same commit as the remote `master` which is currently https://github.com/dbudwin/RoboHome-Web/commit/875000d05832114965dd74af4fcf0f03c35fe3cd.

It may also be possible to do a `cherrypick`, so modify the above commands a little bit to looks like:

```
git checkout page404
git branch -m page404-backup
git remote add upstream https://github.com/dbudwin/RoboHome-Web
git checkout master
git pull upstream master
git checkout page404
git cherry-pick 308c49a28916cb4fe037d70c52c3ebe249b1fabb #This will hopefully take this one commit and put it on top of the remote master in a branch called page404
git push --force-with-lease origin page404
```

2018-10-24 16:22 UTC, dbudwin commented
If it gives you too much trouble trying to remove those extra commits just let me know, I should be able to do it for you a little later.  I don't want you to get frustrated with my obsessiveness for an orderly Git history.  I really appreciate your contributions to my project lately and want to keep you on my good side 😄

2018-10-24 17:30 UTC, kailichiang commented
> ```
> git remote add upstream https://github.com/dbudwin/RoboHome-Web
> git checkout master
> git pull upstream master # Hopefully now your local master matches the remote master
> git checkout page404
> git rebase -i master
> # Do the rebase work here
> git push --force-with-lease origin page404
> ```
> ```
> git checkout page404
> git branch -m page404-backup
> git remote add upstream https://github.com/dbudwin/RoboHome-Web
> git checkout master
> git pull upstream master
> git checkout page404
> git cherry-pick 308c49a28916cb4fe037d70c52c3ebe249b1fabb #This will hopefully take this one commit and put it on top of the remote master in a branch called page404
> git push --force-with-lease origin page404
> ```

In fact, I did the exactly the same thing before. And I just did it again. Unfortunately, it looks worse now... Whatever I did now or before, in the git log of my master, I see one more commit after `875000d`, showing `b803591 - (HEAD -> master, origin/master, origin/HEAD) Merge branch 'master' of https://github.com/dbudwin/RoboHome-Web (6 days ago) <kailichiang>` I have no idea if this is the problem. To make the history clean and clear, I may need to delete my fork and fork from your current master, and the create PR again. If you can do anything from your side to resolve the problem, just do it.

BTW, if I wanna keep contributing, it looks like I have to remove the commit `b803591`, right?

2018-10-24 17:35 UTC, dbudwin commented
I'll fix the extra commits in this PR and the other one later today.  Then it may be easiest for you if you re-clone your fork onto your machine and start fresh for any new work you decide to do.  Git can be frustrating sometimes.

2018-10-25 13:51 UTC, dbudwin commented
I cleaned up your branch a bit and made a few minor changes:

1. I changed the include path for the CSS file to have a leading `/` to fix a problem of the 404 page not looking right if you went to a URL several levels deep like `/a/b`.
2. I added another test to verify the "Go Back" link works as expected, but this actually has a [bug in Laravel](https://github.com/laravel/framework/pull/25616), so I'm just going to leave it for now.

2018-10-25 13:52 UTC, dbudwin approved these changes

2018-10-25 13:52 UTC, merged